document.getElementById("khodamForm").addEventListener("submit", function (e) {
  e.preventDefault();
  const nama = document.getElementById("namaLengkap").value;
  const khodam = generateKhodam(nama);
  document.getElementById(
    "hasil"
  ).innerHTML = `<p>Khodam Untuk Nama ${nama} adalah ${khodam} </p>`;
  document.getElementById("namaLengkap").value = "";
});

function generateKhodam(nama) {
  const khodams = [
    "Harimau Keselek",
    "Maung Buladig",
    "Kambing Belut",
    "Kacang Beledug",
    "Cakcak Tidagor",
    "Uyah Basi",
    "Kambing Gadis",
    "Hayam Berem",
    "Ucing Tidagor",
    "Oray Kacepet",
    "Buaya Tunduh",
    "Hayam Gempa",
    "Ranginang Hajatan",
    "Pakcepak Jeder",
    "Awewe gombel",
    "Ayam halu",
    "Badarawuhi",
    "Nyamuk Gendut",
    "Pocong Ngantuk",
    "Genderuwo Nyanyi Dangdut",
    "Kuntilanak Penakut",
    "Wewe Gombel Penjual Cilok",
    "Jinn Cilik Pencinta Upin Ipin",
    "Tuyul Malas Bekerja",
    "Pocong Fashionista",
    "Genderuwo Penari Jaipong",
    "Kuntilanak Pengemar K-Pop",
    "Wewe Gombel Penjual Gorengan",
    "Pocong Siluman",
    "Tuyul Pencinta Es Krim",
    "Pocong Youtuber",
    "Genderuwo Stand Up Comedian",
    "Kuntilanak TikTokers",
    "Wewe Gombel Influencer",
    "Jinn Cilik Hacker",
    "Tuyul Trader Saham",
    "Pocong Vlogger",
    "Genderuwo Content Creator",
    "Kuntilanak Ngantuk",
    "Wewe Gombel Beauty Vlogger",
    "Jin Cilik Youtuber Gaming",
    "Tuyul Investor Bitcoin",
    "Kucing Garong",
    "Genderuwo Streamer",
    "Kuntilanak Vlogger Traveling",
    "Wewe Gombel Food Vlogger",
    "Jinn Cilik Animator",
    "Tuyul Web Developer",
    "Pocong Influencer Motivasi",
    "Genderuwo Life Coach",
    "Kuntilanak Relationship Coach",
    "Wewe Gombel Financial Advisor",
    "Panda Ngemis",
    "Tuyul Social Media Manager",
    "Pocong SEO Specialist",
    "Genderuwo Graphic Designer",
    "Kuntilanak Video Editor",
    "Wewe Gombel Web Designer",
    "Jinn Cilik App Developer",
    "Tuyul Digital Marketer",
    "Pocong Data Analyst",
    "Genderuwo Business Consultant",
    "Kuntilanak HRD",
    "Wewe Gombel Customer Service",
    "Jinn Cilik Project Manager",
    "Tuyul Entrepreneur",
    "Pocong CEO",
    "Pocong Nyanyi Dangdut",
    "Genderuwo Penari Tiktok",
    "Kuntilanak Gamers",
    "Jin Lampu Aladin Versi Cimahi",
    "Banaspati Penjaga Warteg",
    "Siluman Ular Penjual Cilok",
    "Khodam Semar Pembuat Tempe",
    "Nyi Roro Kidul Penjaga Pantai Ancol",
    "Jin Ifrit Tukang Ojek Online",
    "Khodam Harimau Penjaga Toilet Umum",
    "Tuyul Malas",
    "Jin Cacing",
    "Hantu Pocong Penakut",
    "Genderuwo Galau",
    "Kuntilanak Baper",
    "Jin Lampu Bohong",
    "Banaspati Pemarah",
    "Siluman Ular Penipu",
    "Khodam Semar Pelit",
    "Nyi Roro Kidul Penjual Kerupuk",
    "Khodam Pocong Bersuara Opera",
    "Genderuwo Influencer Instagram",
    "Kuntilanak Youtuber",
    "Jin Lampu Penulis Cerita Horor",
    "Banaspati Ahli Pijat Tradisional",

    // Nama Nama Khodam Lucu yang Jenaka
    "Siluman Ular Penjual Sate",
    "Khodam Semar Stand Up Comedian",
    "Nyi Roro Kidul Penjaga Rental PS",
    "Jin Ifrit Pemain E-Sport",
    "Khodam Harimau Penjaga Rental Mobil",
    "Khodam Iron Man",
    "Genderuwo Captain America",
    "Kuntilanak Black Widow",
    "Jin Lampu Thor",
    "Banaspati Hulk",
    "Siluman Ular Spiderman",
    "Khodam Deadpool",
    "Nyi Roro Kidul Wonder Woman",
    "Jin Ifrit Aquaman",
    "Khodam Batman",
    "Khodam Tuyul Fashionista",
    "Genderuwo Tukang Cukur",
    "Kuntilanak Penjual Gorengan",
    "Jin Lampu Penjaga Warung Kopi",
    "Macan pemarah",
    "Buaya sunda",
    "Beruang sunda",
    "Harimau birahi",
    "Tutup odol",
    "Tutup panci",
    "Kaleng kejepit",
    "Kanebo kering",
    "Kapal karam",
    "Gergaji mesin",
    "Nyi blorong",
    "Jin rawa rontek",
    "Kucing Israel",
    "Capung gila",
    "Tumis kangkung",
    "Jam Dinding Rusak",
    "Gunting Tumpul",
    "Kasur Empuk",
    "Payung Robek",
    "Kulkas Kosong",
    "Piring Pecah",
    "Meja Berdecit",
    "Koper Berat",
    "Topi Melorot",
    "Lem Super Lengket",
    "Keripik Garing",
    "Senter Mati",
    "Kue Kering",
    "Bantal Empuk",
    "Kendi Air",
    "Penggaris Melengkung",
    "Tali Jemuran",
    "Kancut badak",
    "Rayap gendut",
    "Pagar besi",
    "Kunci gembok",
    "LC karaoke",
    "Cicak kawin",
    "Cupang Betina",
    "Sundel Bolong",
    "Tuyul Kesandung",
    "Genderuwo TikTok",
    "Jin Susu Kental Manis",
    "Si Lontong Lumer",
    "Setan Payung Bocor",
    "Jin Es Krim Leleh",
    "Pocong Bersepeda",
    "Kuntilanak Selfie",
    "Tuyul Main PS5",
    "Batu Bata",
    "Remote TV",
    "Kompor Meledak",
    "Helm Nyasar",
    "Gitar Putus Senar",
    "Si Sate Klathak",
    "Genderuwo Tertawa",
    "Jin Penjual Cilok",
    "Setan Jualan Online",
    "Kuntilanak Kecanduan Kopi",
    "Pocong Nyanyi Dangdut",
    "Jin Martabak Telor",
    "Tuyul Kerja Part-Time",
    "Handuk Basah",
    "Kipas Rusak",
    "Jemuran Penuh",
    "Tisu Gulung",
    "Gelas Plastik",
    "Si Bakso Urat",
    "Setan Suka Drama Korea",
    "Genderuwo Nonton Netflix",
    "Jin Donat Kentang",
    "Kuntilanak Pake Kacamata",
    "Pocong Mainan Kucing",
    "Jin Peminum Boba",
    "Tuyul Bersepatu Roda",
    "Si Keripik Pedas",
    "Setan Kolektor Komik",
    "Genderuwo Pemain Basket",
    "Jin Sate Madura",
    "Kuntilanak Nge-Gym",
    "Pocong Ngantor",
    "Tuyul Jago Coding",
    "Si Pizza Keju",
    "Setan Pemilik Cafe",
    "Genderuwo Seniman",
    "Jin Coklat Batangan",
    "Kuntilanak Hobi Makeup",
    "Pocong Main TikTok",
    "Tuyul Kuliah Online",
    "Si Rambutan Manis",
    "Sendal Jepit",
    "Panci Gosong",
    "Guling Gembung",
    "Sarung Bantal",
    "Kaos Oblong",
    "Jin Kipas Angin",
    "Setan Pembeli Pulsa",
    "Kuntilanak Karaoke",
    "Pocong Joget",
    "Ember Bocor",
    "Celana Sobek",
    "Sepeda Tua",
    "Telepon Jadul",
    "Tas Plastik",
    "Kalender Bekas",
    "Pensil Inul",
    "Buku Kusut",
    "Korek Macet",
    "Mangkok Retak",
    "Lemari Penuh",
  ];

  // Create a simple hash function to map the name to a khodam
  const namaHash = nama
    .split("")
    .reduce((acc, char) => acc + char.charCodeAt(0), 0);

  // Use the hash to select a khodam from the array
  const khodamIndex = namaHash % khodams.length;
  return khodams[khodamIndex];
}
